# Generated by Django 4.1.6 on 2023-02-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prec_PEG', '0001_initial'),
        ('prec_Au', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sample_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Au_input_amount', models.FloatField(blank=True, null=True)),
                ('PEG_input_amount', models.FloatField(blank=True, null=True)),
                ('THF_input_amount', models.FloatField(blank=True, null=True)),
                ('taget_output_amount', models.FloatField(blank=True, null=True)),
                ('real_output_amount', models.FloatField(blank=True, null=True)),
                ('Au', models.ManyToManyField(blank=True, null=True, related_name='Au_PEG', to='prec_Au.info')),
                ('PEG', models.ManyToManyField(blank=True, null=True, related_name='Au_PEG', to='prec_PEG.info')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Information',
            },
        ),
    ]
