# Generated by Django 4.1.6 on 2023-02-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Au',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sample_name', models.CharField(blank=True, max_length=50, null=True)),
                ('HAuCl4_input_amount', models.FloatField(blank=True, null=True)),
                ('Toluene_input_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Au',
                'verbose_name_plural': 'Au_Set',
            },
        ),
        migrations.CreateModel(
            name='PEG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sample_name', models.CharField(blank=True, max_length=50, null=True)),
                ('MPEG_input_amount', models.FloatField(blank=True, null=True)),
                ('TGA_input_amount', models.FloatField(blank=True, null=True)),
                ('Toluene_input_amount', models.FloatField(blank=True, null=True)),
                ('operating_temperature', models.FloatField(blank=True, null=True)),
                ('operating_RPM', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration_time', models.TimeField(blank=True, null=True)),
                ('taget_amount', models.FloatField(blank=True, null=True)),
                ('real_output_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PEG',
                'verbose_name_plural': 'PEG_Set',
            },
        ),
        migrations.CreateModel(
            name='Au_PEG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sample_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Au_input_amount', models.FloatField(blank=True, null=True)),
                ('PEG_input_amount', models.FloatField(blank=True, null=True)),
                ('THF_input_amount', models.FloatField(blank=True, null=True)),
                ('taget_output_amount', models.FloatField(blank=True, null=True)),
                ('real_output_amount', models.FloatField(blank=True, null=True)),
                ('Au_content', models.FloatField(blank=True, null=True)),
                ('which_Au', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Au_PEG', to='precursors.au')),
                ('which_PEG', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Au_PEG', to='precursors.peg')),
            ],
            options={
                'verbose_name': 'Au_PEG',
                'verbose_name_plural': 'Au_PEG_Set',
            },
        ),
    ]
