# Generated by Django 4.1.6 on 2023-02-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('precursors', '0001_initial'),
        ('catalysts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICP_OES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ICP_OES',
                'verbose_name_plural': 'ICP_OES_Data',
            },
        ),
        migrations.CreateModel(
            name='SAXS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAXS',
                'verbose_name_plural': 'SAXS_Data',
            },
        ),
        migrations.CreateModel(
            name='TGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('Au_content', models.FloatField(blank=True, null=True)),
                ('which_Au_PEG', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TGA', to='precursors.au_peg')),
            ],
            options={
                'verbose_name': 'TGA',
                'verbose_name_plural': 'TGA_Data',
            },
        ),
        migrations.CreateModel(
            name='TEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('which_catalyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TEM', to='catalysts.catalyst')),
            ],
            options={
                'verbose_name': 'TEM',
                'verbose_name_plural': 'TEM_Data',
            },
        ),
        migrations.CreateModel(
            name='GC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('CO_conversion', models.FloatField(blank=True, null=True)),
                ('which_catalyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GC', to='catalysts.catalyst')),
            ],
            options={
                'verbose_name': 'GC',
                'verbose_name_plural': 'GC_Data',
            },
        ),
        migrations.CreateModel(
            name='BET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('BET_surface_area', models.FloatField(blank=True, null=True)),
                ('which_catalyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BET', to='catalysts.catalyst')),
            ],
            options={
                'verbose_name': 'BET',
                'verbose_name_plural': 'BET_Data',
            },
        ),
    ]
