# Generated by Django 4.1.6 on 2023-02-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalysts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('BET_surface_area', models.FloatField(blank=True, null=True)),
                ('catalyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BET', to='catalysts.catalyst')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'ordering': ['catalyst'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('figure', models.ImageField(blank=True, null=True, upload_to='')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='dataBET.data')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
