# Generated by Django 4.1.6 on 2023-02-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('precursors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sample_name', models.CharField(blank=True, max_length=50, null=True)),
                ('target_Au_content', models.FloatField(blank=True, null=True)),
                ('start_temperature', models.FloatField(blank=True, null=True)),
                ('end_temperature', models.FloatField(blank=True, null=True)),
                ('which_Au_PEG', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Catalysts', to='precursors.au_peg')),
            ],
            options={
                'verbose_name': 'Catalyst',
                'verbose_name_plural': 'Catalyst_Set',
            },
        ),
    ]
