# Generated by Django 4.1.6 on 2023-02-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prec_Au_PEG', '0001_initial'),
        ('catalysts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalyst',
            name='Au_PEG',
            field=models.ManyToManyField(blank=True, null=True, related_name='Catalysts', to='prec_Au_PEG.info'),
        ),
    ]
