# Generated by Django 4.1.6 on 2023-02-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precursors', '0002_remove_au_peg_au_content'),
        ('catalysts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalyst',
            name='target_Au_content',
        ),
        migrations.AddField(
            model_name='catalyst',
            name='mixed_PEG',
            field=models.ManyToManyField(blank=True, to='precursors.au_peg'),
        ),
    ]
